In [1]:
import torch

x = torch.rand(5, 3)
x


tensor([[0.9182, 0.6143, 0.2566],
        [0.7866, 0.6264, 0.3997],
        [0.3135, 0.6526, 0.3385],
        [0.4712, 0.7017, 0.8657],
        [0.1560, 0.0446, 0.1248]])

In [2]:
y = torch.ones(5 ,3)
y

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [3]:
z = torch.zeros(2, 5, 3)
z

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [4]:
q = x.mm(y.t())
q

tensor([[1.7891, 1.7891, 1.7891, 1.7891, 1.7891],
        [1.8127, 1.8127, 1.8127, 1.8127, 1.8127],
        [1.3046, 1.3046, 1.3046, 1.3046, 1.3046],
        [2.0386, 2.0386, 2.0386, 2.0386, 2.0386],
        [0.3254, 0.3254, 0.3254, 0.3254, 0.3254]])

In [5]:
import numpy as np
x_tensor = torch.randn(2, 3)

y_numpy = np.random.randn(2, 3)

torch.cuda.is_available()

False

In [6]:
from torch.autograd import Variable
x = Variable(torch.ones(2, 2), requires_grad=True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [7]:
y = x + 2
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [8]:
z = y * y
z

tensor([[9., 9.],
        [9., 9.]], grad_fn=<MulBackward0>)

In [9]:
t = torch.mean(z)
t

tensor(9., grad_fn=<MeanBackward0>)

In [10]:
t.backward()

In [11]:
# print(z.grad)
# print(y.grad)
print(x.grad)

tensor([[1.5000, 1.5000],
        [1.5000, 1.5000]])


In [12]:
s = Variable(torch.FloatTensor([[0.01, 0.02]]), requires_grad = True)
s

tensor([[0.0100, 0.0200]], requires_grad=True)

In [13]:
x = Variable(torch.ones(2, 2), requires_grad = True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [14]:
for i in range(10):
    s = s.mm(x)
z = torch.mean(s)
z

tensor(15.3600, grad_fn=<MeanBackward0>)

In [15]:
z.backward()

In [16]:
print(x.grad)

tensor([[37.1200, 37.1200],
        [39.6800, 39.6800]])
