In [3]:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F

import matplotlib.pyplot as plt
import numpy as np

In [6]:
# 演示一维卷积： 一维卷积不代表卷积核只有一维，也不代表被卷积的数据也是一维。一维的意思是说卷积的方向是一维的。
# 参考解释： https://blog.csdn.net/amateurSU/article/details/138557901

batch_size = 2  # 多少批文本数据
word_count = 4  # 每批文本包含多少个单词
embedding_dim = 6 # 每个单词用多少维向量来表示

# 一批数据的张量： 行就是这批文本的各个单词， 列就是每个单词的向量表示
#    I Love My Family
#    *  *   *   *
#    *  *   *   *
#    *  *   *   *
input_data = torch.randn(batch_size, embedding_dim, word_count)

in_channels = embedding_dim  # 每个单词的向量维度

# 比如对于如下一批数据， 如果out_channels为5，则会用5个不同的卷积核与这批数据做卷积运算
#  [[ 0.2605, -1.5650, -0.5183, -0.4161],
#   [ 0.3433,  1.5320,  2.0031,  0.3885],
#   [ 2.3063, -0.3679,  0.7549, -0.9822],
#   [ 1.5229,  1.4932, -0.4872,  0.7238],
#   [ 0.6817,  0.1782, -0.5580, -1.0454],
#   [ 1.0688, -1.6322,  0.9375, -0.3195]]

# 卷积核的高度是 in_channels，宽度是kernel_size

# 根据填充padding为1， 步长stride为2，则：
# 第1个卷积核运算结果为：  [0.0839, 0.0000],
# 第2个卷积核运算结果为：  [0.3262, 0.2788],
# 第3个卷积核运算结果为：  [0.0000, 0.0683],
# 第4个卷积核运算结果为：  [0.0000, 0.0000],
# 第5个卷积核运算结果为：  [0.6557, 1.5359],

# 最后把5个卷积核结果 拼接起来就是 5*2维度的矩阵
out_channels = 5  # 卷积的输出通道，也就是有多少个卷积核

kernel_size = 3  # 卷积核的大小，此处指宽度， 实际高度是 in_channels, 也就是卷积核其实是二维的

stride = 2  # 步幅
padding = 1 # 左右填充大小

# 沿着句子中各个单词的方向进行卷积运算， 即input_data的第三个维度
conv1d_layer = nn.Conv1d(in_channels, out_channels, kernel_size, stride, padding)
relu = nn.ReLU()

conv1d_output = conv1d_layer(input_data)
output = relu(conv1d_output)  # 应用激活函数

# in_channels -> out_channel的变换
print('input size: ', input_data.shape)
print(input_data)
print('output size: ', output.shape) #stride 和 padding参数影响输出的第三个维度
print(output)

input size:  torch.Size([2, 6, 4])
tensor([[[ 0.3096,  0.8617,  1.2254, -0.2105],
         [-1.8949, -0.1091, -0.7661,  1.4692],
         [-0.5503, -1.1103,  1.4052,  0.7749],
         [ 0.6824, -0.0054,  0.4503,  0.6455],
         [-0.4070,  0.5998,  1.0913,  1.3325],
         [-0.5041, -1.5843,  0.1123, -0.2241]],

        [[ 0.6990,  0.0096,  1.0308, -0.2351],
         [-0.4213,  1.3469,  0.6599, -1.1754],
         [ 0.1433, -1.1392,  0.5303,  0.9385],
         [ 0.0650,  0.4296,  0.3355,  0.0442],
         [ 0.1942, -1.1055,  1.6111, -0.8924],
         [-2.3008, -0.4419, -0.4863, -1.1813]]])
output size:  torch.Size([2, 5, 2])
tensor([[[0.0000, 0.0000],
         [0.0416, 0.8747],
         [0.0000, 0.8849],
         [1.2750, 0.8732],
         [0.0595, 0.0000]],

        [[0.0000, 0.0345],
         [0.0000, 0.3771],
         [0.2332, 0.2971],
         [0.8123, 0.7903],
         [0.1252, 0.0000]]], grad_fn=<ReluBackward0>)


In [80]:
# 演示二维卷积: in_channels, out_channels, kernel_size
in_channels = 2
input_data = torch.arange(49 * in_channels,dtype=torch.float32).view(1, in_channels, 7, 7) # 四维数据， 第一维表示批次， 第二维输入通道
conv2d_layer = nn.Conv2d(in_channels = in_channels, out_channels = 1, kernel_size = 3)
#conv2d_layer = nn.Conv2d(in_channels = in_channels, out_channels = 1, kernel_size = (3, 3))

# out_channels = 2表示有2个卷积核，每个卷积核大小 in_channels * kernel_size * kernel_size
conv2d_layer2 = nn.Conv2d(in_channels = in_channels, out_channels = 2, kernel_size = 3)


output = conv2d_layer(input_data)
print(input_data.shape)
print(input_data)
print('\n', output.shape)
print(output)
print(list(conv2d_layer.parameters())) # 卷积核权重

output2 = conv2d_layer2(input_data)
print('\n', output2.shape)
print(output2)
print(list(conv2d_layer2.parameters())) # 卷积核权重

torch.Size([1, 2, 7, 7])
tensor([[[[ 0.,  1.,  2.,  3.,  4.,  5.,  6.],
          [ 7.,  8.,  9., 10., 11., 12., 13.],
          [14., 15., 16., 17., 18., 19., 20.],
          [21., 22., 23., 24., 25., 26., 27.],
          [28., 29., 30., 31., 32., 33., 34.],
          [35., 36., 37., 38., 39., 40., 41.],
          [42., 43., 44., 45., 46., 47., 48.]],

         [[49., 50., 51., 52., 53., 54., 55.],
          [56., 57., 58., 59., 60., 61., 62.],
          [63., 64., 65., 66., 67., 68., 69.],
          [70., 71., 72., 73., 74., 75., 76.],
          [77., 78., 79., 80., 81., 82., 83.],
          [84., 85., 86., 87., 88., 89., 90.],
          [91., 92., 93., 94., 95., 96., 97.]]]])

 torch.Size([1, 1, 5, 5])
tensor([[[[-36.8571, -38.3631, -39.8692, -41.3752, -42.8812],
          [-47.3993, -48.9054, -50.4114, -51.9174, -53.4235],
          [-57.9416, -59.4476, -60.9537, -62.4597, -63.9657],
          [-68.4838, -69.9899, -71.4959, -73.0019, -74.5080],
          [-79.0261, -80.5321, -82.03

In [98]:
# 演示二维卷积: padding, padding_mode
img = torch.arange(25, dtype=torch.float32).reshape(1,1,5,5)
print(img)

# 周围填充0
conv_zeros = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=1, bias=False, padding=3, padding_mode='zeros')
conv_zeros.weight = nn.parameter.Parameter(torch.ones((1,1,1,1)))
img_zeros = conv_zeros(img)
print(img_zeros)

# 以边界对称的点来填充
conv_reflect = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=1, bias=False, padding=3, padding_mode='reflect')
conv_reflect.weight = nn.parameter.Parameter(torch.ones((1,1,1,1)))
img_reflect = conv_reflect(img)
print(img_reflect)

# 复制边界的点填充
conv_replicate = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=1, bias=False, padding=3, padding_mode='replicate')
conv_replicate.weight = nn.parameter.Parameter(torch.ones((1,1,1,1)))
img_replicate = conv_replicate(img)
print(img_replicate)

# 循环复制边界另一侧的点来填充
conv_circular = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=1, bias=False, padding=3, padding_mode='circular')
conv_circular.weight = nn.parameter.Parameter(torch.ones((1,1,1,1)))
img_circular = conv_circular(img)
print(img_circular)

tensor([[[[ 0.,  1.,  2.,  3.,  4.],
          [ 5.,  6.,  7.,  8.,  9.],
          [10., 11., 12., 13., 14.],
          [15., 16., 17., 18., 19.],
          [20., 21., 22., 23., 24.]]]])
tensor([[[[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  1.,  2.,  3.,  4.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  5.,  6.,  7.,  8.,  9.,  0.,  0.,  0.],
          [ 0.,  0.,  0., 10., 11., 12., 13., 14.,  0.,  0.,  0.],
          [ 0.,  0.,  0., 15., 16., 17., 18., 19.,  0.,  0.,  0.],
          [ 0.,  0.,  0., 20., 21., 22., 23., 24.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]]]],
       grad_fn=<ConvolutionBackward0>)
tensor([[[[18., 17., 16., 15., 16

In [103]:
# 演示二维卷积: groups
# 对输入通道进行分组，节省一半参数量
in_channels = 4
model = nn.Conv2d(in_channels, out_channels = 8, kernel_size = 1, stride = 1, groups = 2, bias = False)

inputs = torch.ones(1, in_channels, 1, 1)
print(inputs)

# 设置卷积核的权重，也就是对应 out_channels个filter，每个filter对应 in_channels / groups 个卷积核
# 1  2
# 3  4
# 5  6
# 7  8
# 9  10
# 11 12
# 12 13
# 13 14
# 15 16
for param in model.parameters():
    print(param.size())
    param.data = torch.FloatTensor([list(range(1, 17))]).view(8,2,1,1)

output = model(inputs)
print(output)


tensor([[[[1.]],

         [[1.]],

         [[1.]],

         [[1.]]]])
torch.Size([8, 2, 1, 1])
tensor([[[[ 3.]],

         [[ 7.]],

         [[11.]],

         [[15.]],

         [[19.]],

         [[23.]],

         [[27.]],

         [[31.]]]], grad_fn=<ConvolutionBackward0>)
