In [6]:
from torch import nn
import torch
import numpy as np

# 线性变换， y = w*x + b 一般认为，升维不会增加原始数据的信息量，但可以分离噪音和有用的信息量。
# 总结：升维是为了更好的挖掘样本的特征，使样本更具有区分度，从而更易于分类或者回归，
# 在低纬度中难以区分的特征在高维度中可以轻易的区分。在深度学习当中，通过升维分离噪音和有用的信息，
# 再通过网络学习各个维度的权重，从而将有用信息的权重提高，噪音权重降低，最终提取到样本有用的特征。
model = nn.Linear(3, 5)

X = torch.Tensor([
    [0.1, 0.2, 0.3],
    [0.4, 0.5, 0.6]
])

output = model(X)

print(output)
print(model.weight)
print(model.bias)

tensor([[ 0.0583, -0.2376, -0.3189, -0.5925, -0.3195],
        [ 0.1121,  0.0101, -0.4835, -0.7839, -0.2105]],
       grad_fn=<AddmmBackward0>)
Parameter containing:
tensor([[-0.5118,  0.5555,  0.1356],
        [ 0.5215,  0.5238, -0.2196],
        [ 0.1862, -0.3654, -0.3696],
        [-0.2337, -0.0933, -0.3110],
        [-0.2250,  0.2373,  0.3512]], requires_grad=True)
Parameter containing:
tensor([-0.0423, -0.3286, -0.1535, -0.4572, -0.4498], requires_grad=True)
tensor([[ 4.8468e-01, -3.0374e-01,  2.2359e-02],
        [ 4.8068e-01, -1.5312e-01, -3.0677e-02],
        [ 8.6464e-01, -5.2126e-01, -2.6787e-02],
        [ 5.9160e-01, -1.7553e-01, -5.9858e-02],
        [ 7.8783e-01, -1.8064e-01, -1.2395e-01],
        [ 5.9467e-01, -1.0072e-01, -8.7899e-02],
        [ 6.5815e-01, -4.0620e-02, -1.3093e-01],
        [ 4.4082e-01, -2.5039e-01,  1.7836e-02],
        [ 9.0558e-01, -3.6481e-01, -9.7029e-02],
        [ 3.9241e-01, -4.2754e-02, -4.0861e-02],
        [ 7.2518e-01, -5.0551e-01,  1.4390